runmode            : debug
addr               : 6669
name               : apiserver
url                : http://127.0.0.1:6669
max_ping_count     : 10
gorm_max_conns     : 0
gormlog            : true
log:
  writers          : file,stdout
  logger_level     : DEBUG 
  logger_file      : log/apiserver.log
  log_format_text  : false
  rollingPolicy    : size
  log_rotate_date  : 1
  log_rotate_size  : 1024
  log_backup_count : 7
db:
  type             : mysql
  name             : db_apiserver
  host             : 127.0.0.1
  port             : 3306
  user             : root
  passwd           : 123456
  parseTime        : true
  local            : Local
docker_db:
  type             : mysql
  name             : db_apiserver
  host             : 127.0.0.1
  port             : 3306
  user             : root
  passwd           : 123456
  parseTime        : true
  local            : Local

